From 9dfbe4f9488239a23e77ba83e6cf10f1b1416d78 Mon Sep 17 00:00:00 2001
From: Jiri Popelka <jpopelka@redhat.com>
Date: Sun, 14 Sep 2014 14:52:53 +0200
Subject: Python 3 has removed message attribute from built-in exceptions.


diff --git a/printerproperties.py b/printerproperties.py
index 6e54940..41b12c2 100755
--- a/printerproperties.py
+++ b/printerproperties.py
@@ -1333,7 +1333,7 @@ class PrinterPropertiesDialog(GtkGUI):
             # Either the underlying cupsGetPPD2() function returned
             # NULL without setting an IPP error (so it'll be something
             # like a failed connection), or the PPD could not be parsed.
-            if e.message.startswith ("ppd"):
+            if str (e).startswith ("ppd")
                 show_error_dialog (_("Error"),
                                    _("The PPD file for this queue "
                                      "is damaged."),
-- 
cgit v0.10.2

